In [2]:
!pip install numpy

In [13]:
import numpy as np

In [4]:
np.__version__

'1.24.3'

In [5]:
l=[8,5,2,3,4,7,9]

In [6]:
type(l)

list

In [8]:
x=np.array(l)
print(x)

[8 5 2 3 4 7 9]


In [9]:
type(x)

numpy.ndarray

In [11]:
x[5]

7

In [13]:
np.array([5,2,4,6,8])

array([5, 2, 4, 6, 8])

In [14]:
l1=[5,8,3,4,9,7]
l2=[4,2,3,4,9,8]
l3=[8,2,4,6,9,2]

In [15]:
arr=np.array([l1,l2,l3])

In [16]:
arr

array([[5, 8, 3, 4, 9, 7],
       [4, 2, 3, 4, 9, 8],
       [8, 2, 4, 6, 9, 2]])

In [17]:
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
arr.shape

(3, 6)

In [19]:
arr[0:2,1:2]

array([[8],
       [2]])

In [20]:
arr[0:2,0:4]

array([[5, 8, 3, 4],
       [4, 2, 3, 4]])

In [21]:
arr[0:3,3:5]

array([[4, 9],
       [4, 9],
       [6, 9]])

In [23]:
arr

array([[5, 8, 3, 4, 9, 7],
       [4, 2, 3, 4, 9, 8],
       [8, 2, 4, 6, 9, 2]])

In [29]:
arr[0:3,2:4]

array([[3, 4],
       [3, 4],
       [4, 6]])

In [27]:
# Mechanism to create an arry

In [36]:
"""
1.Array()
2.arange()
3.linspace()
4.logspace()
5.zeros()
6.ones()"""

'\n1.Array()\n2.arange()\n3.linspace()\n4.logspace()\n5.zeros()\n6.ones()'

In [39]:
x=np.arange(20)


In [40]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
x=np.arange(0,20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
x=np.arange(1,51)

In [51]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [52]:
x=np.arange(1,51,3)

In [53]:
x

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [54]:
x=np.arange(0,50)

In [55]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [56]:
x=np.arange(0,50).reshape(5,10)

In [57]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
np.linspace(0,50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [60]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [61]:
np.logspace(0,50)

array([1.00000000e+00, 1.04811313e+01, 1.09854114e+02, 1.15139540e+03,
       1.20679264e+04, 1.26485522e+05, 1.32571137e+06, 1.38949549e+07,
       1.45634848e+08, 1.52641797e+09, 1.59985872e+10, 1.67683294e+11,
       1.75751062e+12, 1.84206997e+13, 1.93069773e+14, 2.02358965e+15,
       2.12095089e+16, 2.22299648e+17, 2.32995181e+18, 2.44205309e+19,
       2.55954792e+20, 2.68269580e+21, 2.81176870e+22, 2.94705170e+23,
       3.08884360e+24, 3.23745754e+25, 3.39322177e+26, 3.55648031e+27,
       3.72759372e+28, 3.90693994e+29, 4.09491506e+30, 4.29193426e+31,
       4.49843267e+32, 4.71486636e+33, 4.94171336e+34, 5.17947468e+35,
       5.42867544e+36, 5.68986603e+37, 5.96362332e+38, 6.25055193e+39,
       6.55128557e+40, 6.86648845e+41, 7.19685673e+42, 7.54312006e+43,
       7.90604321e+44, 8.28642773e+45, 8.68511374e+46, 9.10298178e+47,
       9.54095476e+48, 1.00000000e+50])

In [62]:
np.logspace(0,50,2)

array([1.e+00, 1.e+50])

In [63]:
np.logspace(0,50,5)

array([1.00000000e+00, 3.16227766e+12, 1.00000000e+25, 3.16227766e+37,
       1.00000000e+50])

In [64]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [65]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [69]:
np.random.rand(5,8)

array([[0.87181383, 0.99138191, 0.6387892 , 0.25466722, 0.2123349 ,
        0.74936898, 0.66532492, 0.06854233],
       [0.06223332, 0.03168293, 0.5779316 , 0.67278857, 0.3546694 ,
        0.43411104, 0.52817128, 0.00538518],
       [0.98951323, 0.23334337, 0.49998926, 0.5098263 , 0.58368999,
        0.3739691 , 0.54467508, 0.06291153],
       [0.73130582, 0.53396381, 0.80652805, 0.82714165, 0.81780335,
        0.95101699, 0.48915343, 0.41484359],
       [0.17880556, 0.3146955 , 0.6206979 , 0.39711597, 0.71716368,
        0.65126665, 0.12110871, 0.36553941]])

In [4]:
!pip install numpy

In [14]:
np.random.randint(5,50,5)

array([31, 42, 35, 32, 42])

In [15]:
np.random.randn(6)

array([-0.33255379,  0.13305629,  0.6713878 , -1.47759988, -0.76593782,
        1.27352404])

In [16]:
# pandas

In [17]:
!pip install pandas

In [18]:
import pandas as pd
import numpy as np

In [19]:
data=np.arange(0,20)

In [20]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
data=np.arange(0,20).reshape(4,5)

In [24]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
df=pd.DataFrame(data)

In [26]:
df

,0,1,2,3,4
0,0,1,2,3,4
1,5,6,7,8,9
2,10,11,12,13,14
3,15,16,17,18,19


In [31]:
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),
                columns=["cow","dog","goat","sheep","cat"],
                index=["height","weight","size","color"])

In [32]:
df

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [33]:
df.shape

(4, 5)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, height to color
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cow     4 non-null      int64
 1   dog     4 non-null      int64
 2   goat    4 non-null      int64
 3   sheep   4 non-null      int64
 4   cat     4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


In [35]:
df.describe()

,cow,dog,goat,sheep,cat
count,4.000000,4.000000,4.000000,4.000000,4.000000
mean,7.500000,8.500000,9.500000,10.500000,11.500000
std,6.454972,6.454972,6.454972,6.454972,6.454972
min,0.000000,1.000000,2.000000,3.000000,4.000000
25%,3.750000,4.750000,5.750000,6.750000,7.750000
50%,7.500000,8.500000,9.500000,10.500000,11.500000
75%,11.250000,12.250000,13.250000,14.250000,15.250000
max,15.000000,16.000000,17.000000,18.000000,19.000000


In [36]:
df.isnull()

,cow,dog,goat,sheep,cat
height,False,False,False,False,False
weight,False,False,False,False,False
size,False,False,False,False,False
color,False,False,False,False,False


In [37]:
df.isnull().sum()

cow      0
dog      0
goat     0
sheep    0
cat      0
dtype: int64

In [38]:
df.head()

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [39]:
df.head(2)

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9


In [40]:
df.tail(3)

,cow,dog,goat,sheep,cat
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [41]:
df

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [42]:
df["goat"]

height     2
weight     7
size      12
color     17
Name: goat, dtype: int64

In [43]:
df[["dog","cat"]]

,dog,cat
height,1,4
weight,6,9
size,11,14
color,16,19


In [44]:
df.loc["height"]

cow      0
dog      1
goat     2
sheep    3
cat      4
Name: height, dtype: int64

In [46]:
df.loc[["height","color"]]

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
color,15,16,17,18,19


In [47]:
df

,cow,dog,goat,sheep,cat
height,0,1,2,3,4
weight,5,6,7,8,9
size,10,11,12,13,14
color,15,16,17,18,19


In [48]:
df.iloc[1:3,1:3]

,dog,goat
weight,6,7
size,11,12


In [54]:
df.iloc[1:3,2:4]

,goat,sheep
weight,7,8
size,12,13


In [55]:
df1=pd.read_csv("housing[1].csv")

In [56]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND


In [57]:
df1.tail(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND


In [58]:
df1.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY


In [61]:
# How to deal with null or Nan values

In [62]:
import pandas as pd
import numpy as np

In [63]:
d={
    "Ages":[15,50,42,np.nan,45,56],
    "Weight":[45,np.nan,58,85,56,89],
    "Height":[np.nan,78,np.nan,45,56,36],
    "DOB":[1997,2001,2007,1998,2003,np.nan]
}

In [64]:
d

{'Ages': [15, 50, 42, nan, 45, 56],
 'Weight': [45, nan, 58, 85, 56, 89],
 'Height': [nan, 78, nan, 45, 56, 36],
 'DOB': [1997, 2001, 2007, 1998, 2003, nan]}

In [70]:
pd.DataFrame(d)

,Ages,Weight,Height,DOB
0,15.0,45.0,NaN,1997.0
1,50.0,NaN,78.0,2001.0
2,42.0,58.0,NaN,2007.0
3,NaN,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,NaN


In [74]:
df=pd.DataFrame(d)

In [76]:
df.isnull()

,Ages,Weight,Height,DOB
0,False,False,True,False
1,False,True,False,False
2,False,False,True,False
3,True,False,False,False
4,False,False,False,False
5,False,False,False,True


In [77]:
df.isnull().sum()

Ages      1
Weight    1
Height    2
DOB       1
dtype: int64

In [78]:
df.notnull()

,Ages,Weight,Height,DOB
0,True,True,False,True
1,True,False,True,True
2,True,True,False,True
3,False,True,True,True
4,True,True,True,True
5,True,True,True,False


In [79]:
df.notnull().sum()

Ages      5
Weight    5
Height    4
DOB       5
dtype: int64

In [80]:
df.fillna(0)

,Ages,Weight,Height,DOB
0,15.0,45.0,0.0,1997.0
1,50.0,0.0,78.0,2001.0
2,42.0,58.0,0.0,2007.0
3,0.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,0.0


In [81]:
df.fillna(1)

,Ages,Weight,Height,DOB
0,15.0,45.0,1.0,1997.0
1,50.0,1.0,78.0,2001.0
2,42.0,58.0,1.0,2007.0
3,1.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,1.0


In [82]:
df.fillna(method="bfill")

,Ages,Weight,Height,DOB
0,15.0,45.0,78.0,1997.0
1,50.0,58.0,78.0,2001.0
2,42.0,58.0,45.0,2007.0
3,45.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,NaN


In [83]:
df.fillna(method="ffill")

,Ages,Weight,Height,DOB
0,15.0,45.0,NaN,1997.0
1,50.0,45.0,78.0,2001.0
2,42.0,58.0,78.0,2007.0
3,42.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,2003.0


In [85]:
df.interpolate(method="linear",limit_direction="both")

,Ages,Weight,Height,DOB
0,15.0,45.0,78.0,1997.0
1,50.0,51.5,78.0,2001.0
2,42.0,58.0,61.5,2007.0
3,43.5,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,2003.0


In [86]:
df.replace(np.nan,4)

,Ages,Weight,Height,DOB
0,15.0,45.0,4.0,1997.0
1,50.0,4.0,78.0,2001.0
2,42.0,58.0,4.0,2007.0
3,4.0,85.0,45.0,1998.0
4,45.0,56.0,56.0,2003.0
5,56.0,89.0,36.0,4.0


In [90]:
d={
    "Ages":[15,50,42,4,45,56],
    "Weight":[45,np.nan,58,85,56,89],
    "Height":[np.nan,78,np.nan,45,56,36],
    "DOB":[1997,2001,2007,1998,2003,np.nan]
}

In [91]:
df=pd.DataFrame(d)

In [92]:
df.dropna()

,Ages,Weight,Height,DOB
3,4,85.0,45.0,1998.0
4,45,56.0,56.0,2003.0


In [95]:
df.dropna(axis=1)

,Ages
0,15
1,50
2,42
3,4
4,45
5,56
